#!/bin/sh

if [ "X$1" = "Xstart" ]; then
  echo "S10setup: start"

  # Remount / RW
  echo "S10setup: remount / rw"
  mount -o remount,rw /

##Compiler will insert mount commands##

  # Move existing data to new location (Compatibility fix for coming from older builds)
  if [ -e /root/xios ]; then
    echo "S10setup: Move userdata to correct location"
    rm -rf /root/.xbmc
    mv /root/xios/root/.xbmc /root/
    rm -rf /root/xios
    sync
  fi

  echo "S10setup: moving /media"
  # /media is where usb drives mount, move it to /tmp and bind
  mkdir -p /tmp/media
  cp -a /media /tmp/
  mount -o bind /tmp/media /media

  # Check if NetworkManager system folder exists on userdata
  if [ ! -d /root/.sysconfig/NetworkManager ] ; then
    echo "S10setup: Creating .sysconfig folder... "
    mkdir -p /root/.sysconfig/NetworkManager
    cp -a /etc/NetworkManager/* /root/.sysconfig/NetworkManager/
    chmod 544 /root/.sysconfig/NetworkManager/dispatcher.d/*
  fi
  mount -o bind /root/.sysconfig/NetworkManager /etc/NetworkManager

  # Check if favorites.xml exists (TLBB skin-crash at very first run)
  if [ ! -f /root/.xbmc/userdata/favourites.xml ] ; then
    echo -n "touching favorites.xml file ... "
    mkdir -p /root/.xbmc/userdata
    echo "<favourites></favourites>" > /root/.xbmc/userdata/favourites.xml
  fi

  # Boot with performance, then switch to ondemand (kernel bug)
  CPU=/sys/devices/system/cpu
  for i in $CPU/cpu0/cpufreq $CPU/cpu1/cpufreq; do
    echo "S10setup: set cpu scaling governor"
    echo "lagfree" > $i/scaling_governor
    echo "S10setup: set cpu scaling min/max"
    # M6 devices min freq 200Mhz
    echo "200000" > $i/scaling_min_freq
    # M6 devices max out at 1.2-1.5Ghz depending on uboot
    echo "1200000" > $i/scaling_max_freq
  done

  echo "S10setup: done"
fi
